### ISSUE TITLE
[OpenDesign] Profile Picture frame #177 

### ISSUE THREAD

**Issue by klhernandez42** [mozillahispano/equipoCreativo#10]
## Meta:
Create a profile pic frame with the slogan "Once a mozillian, always a mozillian." with Mozilla logo.

## Detalles:
This frame can be used for facebook profile pictures.

## Detalles sobre el estilo:
Check https://www.facebook.com/profilepicframes for existing profile pic frames.

## Fecha de entrega:
Dec 31, 2017.

## Etiqueta:
[Design Needed, frame]

Original: https://github.com/mozilla/OpenDesign/issues/177

**Comment by klhernandez42** [comment]
[Traducción] 
**Meta:**
Crear un marco de foto de perfil con el lema "Once a mozillian, always a mozillian" con el logo de Mozilla.

La idea es que el marco se pueda utilizar para fotos de perfil de Facebook.

**Detalles sobre el estilo:**
Revisar: https://www.facebook.com/profilepicframes for existing profile pic frames.

**Fecha de entrega:**
31/Diciembre/2017

**Etiqueta:**
[Diseño, necesidad, marco]

Original: mozilla/OpenDesign#177

**Comment by Anteojudo** [comment]
Yo creo que puedo ayudar, necesitaría los logos en formato .png y la fuente para que no se diferencia de las otras.
Saludos!

**Comment by Anteojudo** [comment]
¡Dejo por este medio la traducción del marco! Estaré pendiente al hilo por si es necesaria una modificación. 
Saludos.
![mozilla2](https://user-images.githubusercontent.com/13542241/34118934-290c93f6-e3ff-11e7-95f6-5e5cd1a233d5.png)

**Comment by klhernandez42** [comment]
Yo creo que este podemos irlo cerrando, gracias por el apoyo @Anteojudo :100:
