### ISSUE TITLE
Diseño Poster Conferencia sobre Privacidad

### ISSUE THREAD

**Issue by mattdark** [mozillahispano/equipoCreativo#11]
Meta:
Diseñar poster para charla sobre Privacidad que se realizará la próxima semana en México.

Detalles:
Se requiere diseño de poster para charla sobre privacidad que se realizará la próxima semana, para publicar en redes sociales, en seguida más detalles de la actividad:

Título: ¿Por qué la Privacidad en la Web debería importarnos?
Fecha: 19 de Febrero de 2018
Hora: 4:00 PM
Lugar: Punto México Conectado
Dirección: Av. 9a., Sur Poniente No. 256 | Col. Centro, C.P. 29002
Ciudad: Tuxtla Gutiérrez, México

Detalles sobre el estilo:
En Drive se ha subido una propuesta de diseño, que necesita revisión y correcciones. https://drive.google.com/open?id=1U76DMkSDH2ZSBVNLZYYlA6ninmY8oxNm

Fecha de entrega:
En cuanto sea posible.

Etiqueta:
[Design Needed]

**Comment by klhernandez42** [comment]
Siento no haber atendido a tiempo el issue, espero a futuro podamos apoyar en todo caso y esperando no sea la ultima vez dejo aqui la propuesta de lo que hubiera sido en su momento la adaptación que solicitabas.

![privacy](https://user-images.githubusercontent.com/2287630/36630152-6be85194-1927-11e8-9087-397d28a0c44b.png)

Las disculpas al caso y bueno tomando encuenta la fecha de entrega creo que daria por cerrado el issue.
