### ISSUE TITLE
Diseño Logo Comunidad Rust MX

### ISSUE THREAD

**Issue by mattdark** [mozillahispano/equipoCreativo#13]
Meta:
Diseñar logo para Rust MX, comunidad de Rust en México.

Detalles:
Empezaremos a trabajar en el sitio de la comunidad, que publicaremos dentro de pocas semanas y buscamos nuevo logo para la comunidad.

Detalles sobre el estilo:
El logo que usamos actualmente está [aquí](https://avatars0.githubusercontent.com/u/30848907?s=400&u=6bebee3fcbf0b622f96aafffbeb7d4112d512548&v=4). Buscamos un logo diferente, que nos identifique y esté relacionado a la cultura mexicana.

Fecha de entrega:
5 de Octubre

Etiqueta:
[Design Needed]

**Comment by klhernandez42** [comment]
Genial, buscare por armar una propuesta e informare en el grupo de telegram a ver si alguien mas se anima apoyar. :-)

**Comment by klhernandez42** [comment]
![seleccion_094](https://user-images.githubusercontent.com/2287630/45847839-98b1ef80-bce9-11e8-8849-fd32149c3972.png)

Acá mi propuesta @mattdark arriba seria el logo y abajo un posible icon. ¿Que les parece?

**Comment by mayela** [comment]
Se parece mucho al logo que tenemos actualmente.
<img alt="logo" src="https://discourse-paas-production-content.s3.amazonaws.com/original/2X/d/d5384f9d7997038340a3d5f5fc784c9cb956c06a.jpeg">.

Lo queremos cambiar por que el sombrero y el bigote nos parece que representa prejuicios negativos. 

Podríamos intentar quitando el sombrero e integrar y en el engrane agregar algo como el aro más externo de la piedra del sol? O algo que tenga que ver con las culturas prehispánicas o una tradición mexicana. 

![monolito_de_la_piedra_del_sol](https://user-images.githubusercontent.com/665952/46046750-dea2f500-c0e7-11e8-951e-f90e794f37e6.jpg)

**Comment by klhernandez42** [comment]
Comparto tu comentario sobre el estigma de la cultura mexicana, pero no soy del país asi que no tengo una idea más clara de lo que buscan o es más del país. Este recurso que me mandas @mayela me da una mejor idea de lo que necesitan ¿es cultura azteca en Mexico o no?, vere por realizar una adaptación y ya les envio la propuesta.  

Gracias, por la retroalimentación.

**Comment by mayela** [comment]
Muchas gracias por la ayuda @karlalhdz !

**Comment by klhernandez42** [comment]
Perdon la tardanza con el envio de la propuesta pero tuve proyectos que saturaron mi tiempo aqui en mi trabajo.... :-) pero aqui algo que trabaje por si aún les funciona. @mayela @mattdark 
![seleccion_495](https://user-images.githubusercontent.com/2287630/51449138-4fea6180-1cf0-11e9-966f-15675cf8c579.png)

**Comment by mattdark** [comment]
Hola @karlalhdz Muchas gracias por trabajar en la propuesta. Lo compartiré con la comunidad para leer sus opiniones. En lo personal me gustó.

**Comment by klhernandez42** [comment]
Dale, que de gustarles me facilitas un correo para enviarles editable y variaciones por mi usario en telegram https://t.me/klhernandez42 :smile: tambien podria adjuntarselos aqui en el repo del equipo creativo o puedo abrir uno para ustedes me avisas como les sale mejor.

**Comment by klhernandez42** [comment]
¿chicos aun no han podido discutir sobre el logo? para ver si vamos cerrando el issue o se continua

**Comment by klhernandez42** [comment]
ping @mattdark

**Comment by mayela** [comment]
Hola @klhernandez42, muchas gracias por tu trabajo. Me gustó pero nos entregaron otra propuesta antes que ya estamos utilizando.

Lamentó no haberte informado antes.

**Comment by klhernandez42** [comment]
Bueno, esta bien  :-) exitos con la comunidad. Ya con esto puedo dar por cerrado el issue.
