### ISSUE TITLE
Reactivando la comunidad Costa Rica

### ISSUE THREAD

**Issue by daviddagb2** [mozillahispano/equipoCreativo#17]
Recientemente entre en contacto con varios de los colaboradores que Costa Rica que han estado un poco dispersos, la idea es como reactivar una comunidad local con las personas interesadas en Mozilla.

Detalles: Necesitamos un arte y recursos gráficos para promover la comunidad: logo, algunos artes de "Únete a la comunidad Mozilla CR" Y banner para redes sociales.

**Comment by klhernandez42** [comment]
¿que redes sociales tienen en lista?

**Comment by daviddagb2** [comment]
> ¿que redes sociales tienen en lista?

Facebook, Twitter, Telegram y página web

**Comment by daviddagb2** [comment]
:D

**Comment by klhernandez42** [comment]
![16_9_PostUnete_MozillaCostaRica](https://user-images.githubusercontent.com/2287630/66340646-dbe5fd00-e902-11e9-80fe-6e272c703b0b.png)

Todas las adaptaciones se basan de esta imagen y las pueden [descargar](https://github.com/mozillahispano/equipoCreativo/tree/master/Unete_MozillaCostaRica) del repositorio ya estan arriba, cualquier cosa me avisan si les parece ya pueden ir cerrando el issue.

**Comment by daviddagb2** [comment]
Muchas gracias @klhernandez42 te quedaron muy bonitos

**Comment by klhernandez42** [comment]
Chivo, a pues voy ir dando por concluido el issue. :+1:
