### ISSUE TITLE
Banner Firefox OS

### ISSUE THREAD

**Issue by sebastianserna** [mozillahispano/equipoCreativo#4]
https://www.mozilla.org/es-ES/firefox/products/ 
https://www.mozilla.org/es-ES/firefox/os/devices/

**Comment by klhernandez42** [comment]
Yo puedo apoyar con esto... :D ¿el banner es para facebook?

**Comment by marti1125** [comment]
pero FxOS ya fue oO ?

**Comment by klhernandez42** [comment]
como asi que ya fue?

**Comment by marti1125** [comment]
Hola @keikkun4  creo que se refiere a esto:  https://foro.mozilla-hispano.org/t/quitar-el-slide-de-firefox-os/21956

**Comment by klhernandez42** [comment]
Ouh que tristeza... bueno... ni modo entonces. Aun no me la creo que Firefox OS no siga...
