### ISSUE TITLE
Nueva identidad para MozillaVE

### ISSUE THREAD

**Issue by ThePhoenixBird** [mozillahispano/equipoCreativo#8]
## Meta:
Actualizar la identidad de Mozilla Venezuela con un nuevo logotipo y wordmark de acuerdo a los nuevos estilos visuales de Mozilla lanzados durante este año 2017.

## Detalles:
La identidad sera utilizada en nuestra pagina web, redes sociales, tarjetas, presentaciones, diapositivas, etc...

## Detalles sobre el estilo:
Mozilla Venezuela posee un logotipo que esta muy arraigado en nuestros corazones y es el de la "Guacamaya de fuego" [[1](http://mozillavenezuela.org/wp-content/themes/mozve-yoko/images/mascota-mozve.png)] como lo llamamos, es un animal emblemático en Venezuela [[2](https://es.wikipedia.org/wiki/Ara_(animal))] dado a que el trópico es su habitad y se ve sobrevolar naturalmente por casi todas las ciudades del país en bandadas.

Queremos mantener la **Guacamaya** como nuestro animal emblemático, y mantener el **tricolor** (amarillo, azul, rojo) en su plumaje el cual siempre es bastante saturado y brillante, estamos abiertos a cualquier propuesta adaptada a la guiá de estilos visuales de Mozilla 2017 y preferiblemente un diseño plano que sea fácil de utilizar en múltiples sitios ya sea material impreso en papel, camisetas, etc... así como para la web. 

Imágenes de referencia [[3](http://1.bp.blogspot.com/-1gqMFFYH1B8/UpNlS5pA9pI/AAAAAAAAAEc/OboOE4YTzyQ/s1600/Ara_macao_-flying_away.jpg)], [[4](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Ara_macao_qtl1.jpg/800px-Ara_macao_qtl1.jpg)], [[5](https://previews.123rf.com/images/prinprince/prinprince1510/prinprince151000304/46980950-hermosa-ave-guacamaya-roja-con-una-bonita-cola-larga-isoalted-en-el-fondo-blanco-Foto-de-archivo.jpg)], [[6](http://2.bp.blogspot.com/-a6QasqcLs4E/TywRC5yZHbI/AAAAAAAAAB4/0T3s4pTboSE/s1600/guaca.jpg)] 

## Fecha de entrega:
Cuando fuese posible :)

## Etiqueta:
[Logo, ILustración, Banner, Venezuela]

**Comment by klhernandez42** [comment]
Aqui hay una propuesta a dos colores de fondos
![seleccion_179](https://user-images.githubusercontent.com/2287630/33917002-62bda834-df71-11e7-88d1-471719e01ae8.png)

**Comment by barrosgg** [comment]
Hola @karlalhdz, su diseño es increíble! Me gustaría sugerir escribir "venezuela" usando solo Zilla Highlight. Este pájaro es hermoso, ¡felicidades por este trabajo!

**Comment by ajsb85** [comment]
Tenemos una encuesta para decidir el diseño final en el grupo en Telegram

https://t.me/mozilla_venezuela

**Comment by klhernandez42** [comment]
![ave_venezuelamoz](https://user-images.githubusercontent.com/2287630/34609735-7ea05464-f1e3-11e7-8d7c-834811f097ba.png)


Muchas gracias, @barrosgeraldo . Aqui iria con el cambio que me sugeria haciendo uso de Zilla Highlight. Por cierto, @ajsb85 y @ThePhoenixBird  ¿que tal va la encuesta en color a gustado mas?

**Comment by barrosgg** [comment]
Looks great! 🎉

**Comment by pransh15** [comment]
It's beautiful! <3

**Comment by ThePhoenixBird** [comment]
Hemos decidido finalmente por el logotipo con el fondo azul!

Muchas gracias a todos! y especialmente a @karlalhdz por el hermoso logotipo para nuestra comunidad.

Nos ponemos en contacto para que me envies los fuentes?

**Comment by klhernandez42** [comment]
Que buena noticia con el logo, aqui te dejo lo que me pides dentro del repositorio estan las todas las versiones del logo y la del perfil. 
 
[Paquete Logo Mozilla Venezuela](https://github.com/mozillahispano/equipoCreativo/tree/master/MozillaVenezuela_logo)

![seleccion_311](https://user-images.githubusercontent.com/2287630/36188788-26941832-1114-11e8-8c9e-6ccf36ae863b.png)

Creo podemos dar por cerrado este issue.
